import type { Metadata } from 'next'
import './globals.css'
import { SFProText } from './ui/fonts/fonts'

export const metadata: Metadata = {
  title: 'Test assignment',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${SFProText.className} text-base`}>
      <body className={SFProText.variable}>
        <div className="mx-auto my-0 max-w-[698px]">{children}</div>
      </body>
    </html>
  )
}
