import type { Metadata } from 'next'
import './globals.css'
import { SFProText } from './static/fonts/fonts'

export const metadata: Metadata = {
  title: 'Test assignment',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${SFProText.className} text-base`}>
      <body className={SFProText.variable}>
        {children}
        <div id="modal-root" />
      </body>
    </html>
  )
}
